version: '3.8'

services:
  app-node:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    working_dir: /var/www/hortmann-cars
    tty: true
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - ./:/var/www/hortmann-cars